
services:
  # 交互式开发容器
  fuzzer:
    build: .
    image: at-fuzz:latest
    container_name: at-fuzz-dev
    volumes:
      - .:/fuzzer
    working_dir: /fuzzer
    stdin_open: true
    tty: true
    command: /bin/bash